export const countriesList = [
    {
      value: "AD",
      flag: "https://flagcdn.com/w40/ad.png",
      country: { en: "Andorra", ar: "أندورا" },
      phone_code: "376",
      phoneLength: 6,
    },
    {
      value: "AE",
      flag: "https://flagcdn.com/w40/ae.png",
      country: { en: "United Arab Emirates", ar: "الإمارات العربية المتحدة" },
      phone_code: "971",
      phoneLength: 9,
    },
    {
      value: "AF",
      flag: "https://flagcdn.com/w40/af.png",
      country: { en: "Afghanistan", ar: "أفغانستان" },
      phone_code: "93",
      phoneLength: 9,
    },
    {
      value: "AG",
      flag: "https://flagcdn.com/w40/ag.png",
      country: { en: "Antigua and Barbuda", ar: "أنتيغوا وبربودا" },
      phone_code: "1-268",
      phoneLength: 10,
    },
    {
      value: "AI",
      flag: "https://flagcdn.com/w40/ai.png",
      country: { en: "Anguilla", ar: "أنغويلا" },
      phone_code: "1-264",
      phoneLength: 10,
    },
    {
      value: "AL",
      flag: "https://flagcdn.com/w40/al.png",
      country: { en: "Albania", ar: "ألبانيا" },
      phone_code: "355",
      phoneLength: 9,
    },
    {
      value: "AM",
      flag: "https://flagcdn.com/w40/am.png",
      country: { en: "Armenia", ar: "أرمينيا" },
      phone_code: "374",
      phoneLength: 6,
    },
    {
      value: "AO",
      flag: "https://flagcdn.com/w40/ao.png",
      country: { en: "Angola", ar: "أنغولا" },
      phone_code: "244",
      phoneLength: 9,
    },
    {
      value: "AQ",
      flag: "https://flagcdn.com/w40/aq.png",
      country: { en: "Antarctica", ar: "القارة القطبية الجنوبية" },
      phone_code: "672",
      phoneLength: 6,
    },
    {
      value: "AR",
      flag: "https://flagcdn.com/w40/ar.png",
      country: { en: "Argentina", ar: "الأرجنتين" },
      phone_code: "54",
      phoneLength: [6, 7, 8],
    },
    {
      value: "AS",
      flag: "https://flagcdn.com/w40/as.png",
      country: { en: "American Samoa", ar: "ساموا الأمريكية" },
      phone_code: "1-684",
      phoneLength: 10,
    },
    {
      value: "AT",
      flag: "https://flagcdn.com/w40/at.png",
      country: { en: "Austria", ar: "النمسا" },
      phone_code: "43",
      phoneLength: [10, 11],
    },
    {
      value: "AU",
      flag: "https://flagcdn.com/w40/au.png",
      country: { en: "Australia", ar: "أستراليا" },
      phone_code: "61",
      suggested: true,
      phoneLength: 9,
    },
    {
      value: "AW",
      flag: "https://flagcdn.com/w40/aw.png",
      country: { en: "Aruba", ar: "أروبا" },
      phone_code: "297",
      phoneLength: 7,
    },
    {
      value: "AX",
      flag: "https://flagcdn.com/w40/ax.png",
      country: { en: "Alland Islands", ar: "جزر آلاند" },
      phone_code: "358",
      min: 7,
      max: 10,
    },
    {
      value: "AZ",
      flag: "https://flagcdn.com/w40/az.png",
      country: { en: "Azerbaijan", ar: "أذربيجان" },
      phone_code: "994",
      phoneLength: 9,
    },
    {
      value: "BA",
      flag: "https://flagcdn.com/w40/ba.png",
      country: { en: "Bosnia and Herzegovina", ar: "البوسنة والهرسك" },
      phone_code: "387",
      phoneLength: 8,
    },
    {
      value: "BB",
      flag: "https://flagcdn.com/w40/bb.png",
      country: { en: "Barbados", ar: "بربادوس" },
      phone_code: "1-246",
      phoneLength: 10,
    },
    {
      value: "BD",
      flag: "https://flagcdn.com/w40/bd.png",
      country: { en: "Bangladesh", ar: "بنغلاديش" },
      phone_code: "880",
      phoneLength: 10,
    },
    {
      value: "BE",
      flag: "https://flagcdn.com/w40/be.png",
      country: { en: "Belgium", ar: "بلجيكا" },
      phone_code: "32",
      phoneLength: 9,
    },
    {
      value: "BF",
      flag: "https://flagcdn.com/w40/bf.png",
      country: { en: "Burkina Faso", ar: "بوركينا فاسو" },
      phone_code: "226",
      phoneLength: 8,
    },
    {
      value: "BG",
      flag: "https://flagcdn.com/w40/bg.png",
      country: { en: "Bulgaria", ar: "بلغاريا" },
      phone_code: "359",
      phoneLength: 9,
    },
    {
      value: "BH",
      flag: "https://flagcdn.com/w40/bh.png",
      country: { en: "Bahrain", ar: "البحرين" },
      phone_code: "973",
      phoneLength: 8,
    },
    {
      value: "BI",
      flag: "https://flagcdn.com/w40/bi.png",
      country: { en: "Burundi", ar: "بوروندي" },
      phone_code: "257",
      phoneLength: 8,
    },
    {
      value: "BJ",
      flag: "https://flagcdn.com/w40/bj.png",
      country: { en: "Benin", ar: "بنين" },
      phone_code: "229",
      phoneLength: 8,
    },
    {
      value: "BL",
      flag: "https://flagcdn.com/w40/bl.png",
      country: { en: "Saint Barthelemy", ar: "سان بارتيليمي" },
      phone_code: "590",
      phoneLength: 9,
    },
    {
      value: "BM",
      flag: "https://flagcdn.com/w40/bm.png",
      country: { en: "Bermuda", ar: "برمودا" },
      phone_code: "1-441",
      phoneLength: 10,
    },
    {
      value: "BN",
      flag: "https://flagcdn.com/w40/bn.png",
      country: { en: "Brunei Darussalam", ar: "بروناي" },
      phone_code: "673",
      phoneLength: 7,
    },
    {
      value: "BO",
      flag: "https://flagcdn.com/w40/bo.png",
      country: { en: "Bolivia", ar: "بوليفيا" },
      phone_code: "591",
      phoneLength: 9,
    },
    {
      value: "BR",
      flag: "https://flagcdn.com/w40/br.png",
      country: { en: "Brazil", ar: "البرازيل" },
      phone_code: "55",
      phoneLength: 11,
    },
    {
      value: "BS",
      flag: "https://flagcdn.com/w40/bs.png",
      country: { en: "Bahamas", ar: "جزر البهاما" },
      phone_code: "1-242",
      phoneLength: 10,
    },
    {
      value: "BT",
      flag: "https://flagcdn.com/w40/bt.png",
      country: { en: "Bhutan", ar: "بوتان" },
      phone_code: "975",
      phoneLength: 7,
    },
    {
      value: "BV",
      flag: "https://flagcdn.com/w40/bv.png",
      country: { en: "Bouvet Island", ar: "جزيرة بوفيت" },
      phone_code: "47",
      phoneLength: 10,
    },
    {
      value: "BW",
      flag: "https://flagcdn.com/w40/bw.png",
      country: { en: "Botswana", ar: "بوتسوانا" },
      phone_code: "267",
      phoneLength: 7,
    },
    {
      value: "BY",
      flag: "https://flagcdn.com/w40/by.png",
      country: { en: "Belarus", ar: "روسيا البيضاء" },
      phone_code: "375",
      phoneLength: 9,
    },
    {
      value: "BZ",
      flag: "https://flagcdn.com/w40/bz.png",
      country: { en: "Belize", ar: "بليز" },
      phone_code: "501",
      phoneLength: 7,
    },
    {
      value: "CA",
      flag: "https://flagcdn.com/w40/ca.png",
      country: { en: "Canada", ar: "كندا" },
      phone_code: "1",
      suggested: true,
      phoneLength: 10,
    },
    {
      value: "CC",
      flag: "https://flagcdn.com/w40/cc.png",
      country: { en: "Cocos (Keeling) Islands", ar: "جزر كوكوس" },
      phone_code: "61",
      phoneLength: 10,
    },
    {
      value: "CD",
      flag: "https://flagcdn.com/w40/cd.png",
      country: {
        en: "Congo, Democratic Republic of the",
        ar: "جمهورية الكونغو الديمقراطية",
      },
      phone_code: "243",
      phoneLength: 7,
    },
    {
      value: "CF",
      flag: "https://flagcdn.com/w40/cf.png",
      country: { en: "Central African Republic", ar: "جمهورية أفريقيا الوسطى" },
      phone_code: "236",
      phoneLength: 8,
    },
    {
      value: "CG",
      flag: "https://flagcdn.com/w40/cg.png",
      country: { en: "Congo, Republic of the", ar: "جمهورية الكونغو" },
      phone_code: "242",
      phoneLength: 9,
    },
    {
      value: "CH",
      flag: "https://flagcdn.com/w40/ch.png",
      country: { en: "Switzerland", ar: "سويسرا" },
      phone_code: "41",
      phoneLength: 9,
    },
    {
      value: "CI",
      flag: "https://flagcdn.com/w40/ci.png",
      country: { en: "Cote d'Ivoire", ar: "ساحل العاج" },
      phone_code: "225",
      phoneLength: 8,
    },
    {
      value: "CK",
      flag: "https://flagcdn.com/w40/ck.png",
      country: { en: "Cook Islands", ar: "جزر كوك" },
      phone_code: "682",
      phoneLength: 5,
    },
    {
      value: "CL",
      flag: "https://flagcdn.com/w40/cl.png",
      country: { en: "Chile", ar: "تشيلي" },
      phone_code: "56",
      phoneLength: 9,
    },
    {
      value: "CM",
      flag: "https://flagcdn.com/w40/cm.png",
      country: { en: "Cameroon", ar: "الكاميرون" },
      phone_code: "237",
      phoneLength: 9,
    },
    {
      value: "CN",
      flag: "https://flagcdn.com/w40/cn.png",
      country: { en: "China", ar: "الصين" },
      phone_code: "86",
      phoneLength: 11,
    },
    {
      value: "CO",
      flag: "https://flagcdn.com/w40/co.png",
      country: { en: "Colombia", ar: "كولومبيا" },
      phone_code: "57",
      phoneLength: 10,
    },
    {
      value: "CR",
      flag: "https://flagcdn.com/w40/cr.png",
      country: { en: "Costa Rica", ar: "كوستاريكا" },
      phone_code: "506",
      phoneLength: 8,
    },
    {
      value: "CU",
      flag: "https://flagcdn.com/w40/cu.png",
      country: { en: "Cuba", ar: "كوبا" },
      phone_code: "53",
      phoneLength: 8,
    },
    {
      value: "CV",
      flag: "https://flagcdn.com/w40/cv.png",
      country: { en: "Cape Verde", ar: "الرأس الأخضر" },
      phone_code: "238",
      phoneLength: 7,
    },
    {
      value: "CW",
      flag: "https://flagcdn.com/w40/cw.png",
      country: { en: "Curacao", ar: "كوراساو" },
      phone_code: "599",
      phoneLength: 7,
    },
    {
      value: "CX",
      flag: "https://flagcdn.com/w40/cx.png",
      country: { en: "Christmas Island", ar: "جزيرة الكريسماس" },
      phone_code: "61",
      phoneLength: 9,
    },
    {
      value: "CY",
      flag: "https://flagcdn.com/w40/cy.png",
      country: { en: "Cyprus", ar: "قبرص" },
      phone_code: "357",
      phoneLength: 8,
    },
    {
      value: "CZ",
      flag: "https://flagcdn.com/w40/cz.png",
      country: { en: "Czech Republic", ar: "جمهورية التشيك" },
      phone_code: "420",
      phoneLength: 9,
    },
    {
      value: "DE",
      flag: "https://flagcdn.com/w40/de.png",
      country: { en: "Germany", ar: "ألمانيا" },
      phone_code: "49",
      suggested: true,
      phoneLength: 10,
    },
    {
      value: "DJ",
      flag: "https://flagcdn.com/w40/dj.png",
      country: { en: "Djibouti", ar: "جيبوتي" },
      phone_code: "253",
      phoneLength: 10,
    },
    {
      value: "DK",
      flag: "https://flagcdn.com/w40/dk.png",
      country: { en: "Denmark", ar: "الدنمارك" },
      phone_code: "45",
      phoneLength: 8,
    },
    {
      value: "DM",
      flag: "https://flagcdn.com/w40/dm.png",
      country: { en: "Dominica", ar: "دومينيكا" },
      phone_code: "1-767",
      phoneLength: 10,
    },
    {
      value: "DO",
      flag: "https://flagcdn.com/w40/do.png",
      country: { en: "Dominican Republic", ar: "جمهورية الدومينيكان" },
      phone_code: "1-809",
      phoneLength: 10,
    },
    {
      value: "DZ",
      flag: "https://flagcdn.com/w40/dz.png",
      country: { en: "Algeria", ar: "الجزائر" },
      phone_code: "213",
      phoneLength: 9,
    },
    {
      value: "EC",
      flag: "https://flagcdn.com/w40/ec.png",
      country: { en: "Ecuador", ar: "الإكوادور" },
      phone_code: "593",
      phoneLength: 9,
    },
    {
      value: "EE",
      flag: "https://flagcdn.com/w40/ee.png",
      country: { en: "Estonia", ar: "إستونيا" },
      phone_code: "372",
      phoneLength: 8,
    },
    {
      value: "EG",
      flag: "https://flagcdn.com/w40/eg.png",
      country: { en: "Egypt", ar: "مصر" },
      phone_code: "20",
      phoneLength: 10,
    },
    {
      value: "EH",
      flag: "https://flagcdn.com/w40/eh.png",
      country: { en: "Western Sahara", ar: "الصحراء الغربية" },
      phone_code: "212",
      phoneLength: 9,
    },
    {
      value: "ER",
      flag: "https://flagcdn.com/w40/er.png",
      country: { en: "Eritrea", ar: "إريتريا" },
      phone_code: "291",
      phoneLength: 7,
    },
    {
      value: "ES",
      flag: "https://flagcdn.com/w40/es.png",
      country: { en: "Spain", ar: "إسبانيا" },
      phone_code: "34",
      phoneLength: 9,
    },
    {
      value: "ET",
      flag: "https://flagcdn.com/w40/et.png",
      country: { en: "Ethiopia", ar: "إثيوبيا" },
      phone_code: "251",
      phoneLength: 9,
    },
    {
      value: "FI",
      flag: "https://flagcdn.com/w40/fi.png",
      country: { en: "Finland", ar: "فنلندا" },
      phone_code: "358",
      min: 9,
      max: 11,
    },
    {
      value: "FJ",
      flag: "https://flagcdn.com/w40/fj.png",
      country: { en: "Fiji", ar: "فيجي" },
      phone_code: "679",
      phoneLength: 7,
    },
    {
      value: "FK",
      flag: "https://flagcdn.com/w40/fk.png",
      country: { en: "Falkland Islands (Malvinas)", ar: "جزر فوكلاند" },
      phone_code: "500",
      phoneLength: 5,
    },
    {
      value: "FM",
      flag: "https://flagcdn.com/w40/fm.png",
      country: { en: "Micronesia, Federated States of", ar: "ميكرونيزيا" },
      phone_code: "691",
      phoneLength: 7,
    },
    {
      value: "FO",
      flag: "https://flagcdn.com/w40/fo.png",
      country: { en: "Faroe Islands", ar: "جزر فارو" },
      phone_code: "298",
      phoneLength: 5,
    },
    {
      value: "FR",
      flag: "https://flagcdn.com/w40/fr.png",
      country: { en: "France", ar: "فرنسا" },
      phone_code: "33",
      suggested: true,
      phoneLength: 9,
    },
    {
      value: "GA",
      flag: "https://flagcdn.com/w40/ga.png",
      country: { en: "Gabon", ar: "الغابون" },
      phone_code: "241",
      phoneLength: 7,
    },
    {
      value: "GB",
      flag: "https://flagcdn.com/w40/gb.png",
      country: { en: "United Kingdom", ar: "المملكة المتحدة" },
      phone_code: "44",
      phoneLength: 10,
    },
    {
      value: "GD",
      flag: "https://flagcdn.com/w40/gd.png",
      country: { en: "Grenada", ar: "غرينادا" },
      phone_code: "1-473",
      phoneLength: 10,
    },
    {
      value: "GE",
      flag: "https://flagcdn.com/w40/ge.png",
      country: { en: "Georgia", ar: "جورجيا" },
      phone_code: "995",
      phoneLength: 9,
    },
    {
      value: "GF",
      flag: "https://flagcdn.com/w40/gf.png",
      country: { en: "French Guiana", ar: "غويانا الفرنسية" },
      phone_code: "594",
      phoneLength: 9,
    },
    {
      value: "GG",
      flag: "https://flagcdn.com/w40/gg.png",
      country: { en: "Guernsey", ar: "غيرنزي" },
      phone_code: "44",
      phoneLength: 10,
    },
    {
      value: "GH",
      flag: "https://flagcdn.com/w40/gh.png",
      country: { en: "Ghana", ar: "غانا" },
      phone_code: "233",
      phoneLength: 9,
    },
    {
      value: "GI",
      flag: "https://flagcdn.com/w40/gi.png",
      country: { en: "Gibraltar", ar: "جبل طارق" },
      phone_code: "350",
      phoneLength: 8,
    },
    {
      value: "GL",
      flag: "https://flagcdn.com/w40/gl.png",
      country: { en: "Greenland", ar: "غرينلاند" },
      phone_code: "299",
      phoneLength: 6,
    },
    {
      value: "GM",
      flag: "https://flagcdn.com/w40/gm.png",
      country: { en: "Gambia", ar: "غامبيا" },
      phone_code: "220",
      phoneLength: 7,
    },
    {
      value: "GN",
      flag: "https://flagcdn.com/w40/gn.png",
      country: { en: "Guinea", ar: "غينيا" },
      phone_code: "224",
      phoneLength: 9,
    },
    {
      value: "GP",
      flag: "https://flagcdn.com/w40/gp.png",
      country: { en: "Guadeloupe", ar: "غوادلوب" },
      phone_code: "590",
      phoneLength: 9,
    },
    {
      value: "GQ",
      flag: "https://flagcdn.com/w40/gq.png",
      country: { en: "Equatorial Guinea", ar: "غينيا الاستوائية" },
      phone_code: "240",
      phoneLength: 9,
    },
    {
      value: "GR",
      flag: "https://flagcdn.com/w40/gr.png",
      country: { en: "Greece", ar: "اليونان" },
      phone_code: "30",
      phoneLength: 10,
    },
    {
      value: "GS",
      flag: "https://flagcdn.com/w40/gs.png",
      country: {
        en: "South Georgia and the South Sandwich Islands",
        ar: "جورجيا الجنوبية وجزر ساندويتش الجنوبية",
      },
      phone_code: "500",
      phoneLength: 5,
    },
    {
      value: "GT",
      flag: "https://flagcdn.com/w40/gt.png",
      country: { en: "Guatemala", ar: "غواتيمالا" },
      phone_code: "502",
      phoneLength: 8,
    },
    {
      value: "GU",
      flag: "https://flagcdn.com/w40/gu.png",
      country: { en: "Guam", ar: "غوام" },
      phone_code: "1-671",
      phoneLength: 10,
    },
    {
      value: "GW",
      flag: "https://flagcdn.com/w40/gw.png",
      country: { en: "Guinea-Bissau", ar: "غينيا بيساو" },
      phone_code: "245",
      phoneLength: 9,
    },
    {
      value: "GY",
      flag: "https://flagcdn.com/w40/gy.png",
      country: { en: "Guyana", ar: "غيانا" },
      phone_code: "592",
      phoneLength: 7,
    },
    {
      value: "HK",
      flag: "https://flagcdn.com/w40/hk.png",
      country: { en: "Hong Kong", ar: "هونغ كونغ" },
      phone_code: "852",
      phoneLength: 8,
    },
    {
      value: "HM",
      flag: "https://flagcdn.com/w40/hm.png",
      country: {
        en: "Heard Island and McDonald Islands",
        ar: "جزيرة هيرد وجزر ماكدونالد",
      },
      phone_code: "672",
      phoneLength: 10,
    },
    {
      value: "HN",
      flag: "https://flagcdn.com/w40/hn.png",
      country: { en: "Honduras", ar: "هندوراس" },
      phone_code: "504",
      phoneLength: 8,
    },
    {
      value: "HR",
      flag: "https://flagcdn.com/w40/hr.png",
      country: { en: "Croatia", ar: "كرواتيا" },
      phone_code: "385",
      phoneLength: 9,
    },
    {
      value: "HT",
      flag: "https://flagcdn.com/w40/ht.png",
      country: { en: "Haiti", ar: "هايتي" },
      phone_code: "509",
      phoneLength: 8,
    },
    {
      value: "HU",
      flag: "https://flagcdn.com/w40/hu.png",
      country: { en: "Hungary", ar: "المجر" },
      phone_code: "36",
      phoneLength: 9,
    },
    {
      value: "ID",
      flag: "https://flagcdn.com/w40/id.png",
      country: { en: "Indonesia", ar: "إندونيسيا" },
      phone_code: "62",
      phoneLength: 11,
    },
    {
      value: "IE",
      flag: "https://flagcdn.com/w40/ie.png",
      country: { en: "Ireland", ar: "أيرلندا" },
      phone_code: "353",
      phoneLength: 9,
    },
    {
      value: "IL",
      flag: "https://flagcdn.com/w40/il.png",
      country: { en: "Israel", ar: "إسرائيل" },
      phone_code: "972",
      phoneLength: 9,
    },
    {
      value: "IM",
      flag: "https://flagcdn.com/w40/im.png",
      country: { en: "Isle of Man", ar: "جزيرة مان" },
      phone_code: "44",
      phoneLength: 10,
    },
    {
      value: "IN",
      flag: "https://flagcdn.com/w40/in.png",
      country: { en: "India", ar: "الهند" },
      phone_code: "91",
      phoneLength: 10,
    },
    {
      value: "IO",
      flag: "https://flagcdn.com/w40/io.png",
      country: {
        en: "British Indian Ocean Territory",
        ar: "إقليم المحيط البريطاني الهندي",
      },
      phone_code: "246",
      phoneLength: 7,
    },
    {
      value: "IQ",
      flag: "https://flagcdn.com/w40/iq.png",
      country: { en: "Iraq", ar: "العراق" },
      phone_code: "964",
      phoneLength: 10,
    },
    {
      value: "IR",
      flag: "https://flagcdn.com/w40/ir.png",
      country: { en: "Iran, Islamic Republic of", ar: "إيران" },
      phone_code: "98",
      phoneLength: 11,
    },
    {
      value: "IS",
      flag: "https://flagcdn.com/w40/is.png",
      country: { en: "Iceland", ar: "آيسلندا" },
      phone_code: "354",
      phoneLength: 7,
    },
    {
      value: "IT",
      flag: "https://flagcdn.com/w40/it.png",
      country: { en: "Italy", ar: "إيطاليا" },
      phone_code: "39",
      phoneLength: 10,
    },
    {
      value: "JE",
      flag: "https://flagcdn.com/w40/je.png",
      country: { en: "Jersey", ar: "جيرسي" },
      phone_code: "44",
      phoneLength: 10,
    },
    {
      value: "JM",
      flag: "https://flagcdn.com/w40/jm.png",
      country: { en: "Jamaica", ar: "جامايكا" },
      phone_code: "1-876",
      phoneLength: 10,
    },
    {
      value: "JO",
      flag: "https://flagcdn.com/w40/jo.png",
      country: { en: "Jordan", ar: "الأردن" },
      phone_code: "962",
      phoneLength: [8, 9],
    },
    {
      value: "JP",
      flag: "https://flagcdn.com/w40/jp.png",
      country: { en: "Japan", ar: "اليابان" },
      phone_code: "81",
      suggested: true,
    },
    {
      value: "KE",
      flag: "https://flagcdn.com/w40/ke.png",
      country: { en: "Kenya", ar: "كينيا" },
      phone_code: "254",
      phoneLength: 10,
    },
    {
      value: "KG",
      flag: "https://flagcdn.com/w40/kg.png",
      country: { en: "Kyrgyzstan", ar: "قيرغيزستان" },
      phone_code: "996",
      phoneLength: 9,
    },
    {
      value: "KH",
      flag: "https://flagcdn.com/w40/kh.png",
      country: { en: "Cambodia", ar: "كمبوديا" },
      phone_code: "855",
      phoneLength: 9,
    },
    {
      value: "KI",
      flag: "https://flagcdn.com/w40/ki.png",
      country: { en: "Kiribati", ar: "كيريباتي" },
      phone_code: "686",
      phoneLength: 8,
    },
    {
      value: "KM",
      flag: "https://flagcdn.com/w40/km.png",
      country: { en: "Comoros", ar: "جزر القمر" },
      phone_code: "269",
      phoneLength: 7,
    },
    {
      value: "KN",
      flag: "https://flagcdn.com/w40/kn.png",
      country: { en: "Saint Kitts and Nevis", ar: "سانت كيتس ونيفيس" },
      phone_code: "1-869",
      phoneLength: 10,
    },
    {
      value: "KP",
      flag: "https://flagcdn.com/w40/kp.png",
      country: {
        en: "Korea, Democratic People's Republic of",
        ar: "كوريا الشمالية",
      },
      phone_code: "850",
      phoneLength: [4, 6, 7, 13],
    },
    {
      value: "KR",
      flag: "https://flagcdn.com/w40/kr.png",
      country: { en: "Korea, Republic of", ar: "كوريا الجنوبية" },
      phone_code: "82",
      phoneLength: [7, 8],
    },
    {
      value: "KW",
      flag: "https://flagcdn.com/w40/kw.png",
      country: { en: "Kuwait", ar: "الكويت" },
      phone_code: "965",
      phoneLength: 8,
    },
    {
      value: "KY",
      flag: "https://flagcdn.com/w40/ky.png",
      country: { en: "Cayman Islands", ar: "جزر كايمان" },
      phone_code: "1-345",
      phoneLength: 7,
    },
    {
      value: "KZ",
      flag: "https://flagcdn.com/w40/kz.png",
      country: { en: "Kazakhstan", ar: "كازاخستان" },
      phone_code: "7",
      phoneLength: 10,
    },
    {
      value: "LA",
      flag: "https://flagcdn.com/w40/la.png",
      country: { en: "Lao People's Democratic Republic", ar: "لاوس" },
      phone_code: "856",
      phoneLength: [8, 9],
    },
    {
      value: "LB",
      flag: "https://flagcdn.com/w40/lb.png",
      country: { en: "Lebanon", ar: "لبنان" },
      phone_code: "961",
      phoneLength: [7, 8],
    },
    {
      value: "LC",
      flag: "https://flagcdn.com/w40/lc.png",
      country: { en: "Saint Lucia", ar: "سانت لوسيا" },
      phone_code: "1-758",
      phoneLength: 7,
    },
    {
      value: "LI",
      flag: "https://flagcdn.com/w40/li.png",
      country: { en: "Liechtenstein", ar: "ليختنشتاين" },
      phone_code: "423",
      phoneLength: 7,
    },
    {
      value: "LK",
      flag: "https://flagcdn.com/w40/lk.png",
      country: { en: "Sri Lanka", ar: "سريلانكا" },
      phone_code: "94",
      phoneLength: 7,
    },
    {
      value: "LR",
      flag: "https://flagcdn.com/w40/lr.png",
      country: { en: "Liberia", ar: "ليبيريا" },
      phone_code: "231",
      phoneLength: [8, 9],
    },
    {
      value: "LS",
      flag: "https://flagcdn.com/w40/ls.png",
      country: { en: "Lesotho", ar: "ليسوتو" },
      phone_code: "266",
      phoneLength: 8,
    },
    {
      value: "LT",
      flag: "https://flagcdn.com/w40/lt.png",
      country: { en: "Lithuania", ar: "ليتوانيا" },
      phone_code: "370",
      phoneLength: 8,
    },
    {
      value: "LU",
      flag: "https://flagcdn.com/w40/lu.png",
      country: { en: "Luxembourg", ar: "لوكسمبورغ" },
      phone_code: "352",
      phoneLength: 9,
    },
    {
      value: "LV",
      flag: "https://flagcdn.com/w40/lv.png",
      country: { en: "Latvia", ar: "لاتفيا" },
      phone_code: "371",
      phoneLength: 8,
    },
    {
      value: "LY",
      flag: "https://flagcdn.com/w40/ly.png",
      country: { en: "Libya", ar: "ليبيا" },
      phone_code: "218",
      phoneLength: 10,
    },
    {
      value: "MA",
      flag: "https://flagcdn.com/w40/ma.png",
      country: { en: "Morocco", ar: "المغرب" },
      phone_code: "212",
      phoneLength: 9,
    },
    {
      value: "MC",
      flag: "https://flagcdn.com/w40/mc.png",
      country: { en: "Monaco", ar: "موناكو" },
      phone_code: "377",
      phoneLength: 8,
    },
    {
      value: "MD",
      flag: "https://flagcdn.com/w40/md.png",
      country: { en: "Moldova, Republic of", ar: "مولدوفا" },
      phone_code: "373",
      phoneLength: 8,
    },
    {
      value: "ME",
      flag: "https://flagcdn.com/w40/me.png",
      country: { en: "Montenegro", ar: "الجبل الأسود" },
      phone_code: "382",
      phoneLength: 8,
    },
    {
      value: "MF",
      flag: "https://flagcdn.com/w40/mf.png",
      country: { en: "Saint Martin (French part)", ar: "سان مارتن" },
      phone_code: "590",
      phoneLength: 6,
    },
    {
      value: "MG",
      flag: "https://flagcdn.com/w40/mg.png",
      country: { en: "Madagascar", ar: "مدغشقر" },
      phone_code: "261",
      phoneLength: 7,
    },
    {
      value: "MH",
      flag: "https://flagcdn.com/w40/mh.png",
      country: { en: "Marshall Islands", ar: "جزر مارشال" },
      phone_code: "692",
      phoneLength: 7,
    },
    {
      value: "MK",
      flag: "https://flagcdn.com/w40/mk.png",
      country: {
        en: "Macedonia, the Former Yugoslav Republic of",
        ar: "مقدونيا",
      },
      phone_code: "389",
      phoneLength: 8,
    },
    {
      value: "ML",
      flag: "https://flagcdn.com/w40/ml.png",
      country: { en: "Mali", ar: "مالي" },
      phone_code: "223",
      phoneLength: 8,
    },
    {
      value: "MM",
      flag: "https://flagcdn.com/w40/mm.png",
      country: { en: "Myanmar", ar: "ميانمار" },
      phone_code: "95",
      min: 7,
      max: 10,
    },
    {
      value: "MN",
      flag: "https://flagcdn.com/w40/mn.png",
      country: { en: "Mongolia", ar: "منغوليا" },
      phone_code: "976",
      phoneLength: 8,
    },
    {
      value: "MO",
      flag: "https://flagcdn.com/w40/mo.png",
      country: { en: "Macao", ar: "ماكاو" },
      phone_code: "853",
      phoneLength: 8,
    },
    {
      value: "MP",
      flag: "https://flagcdn.com/w40/mp.png",
      country: { en: "Northern Mariana Islands", ar: "جزر ماريانا الشمالية" },
      phone_code: "1-670",
      phoneLength: 7,
    },
    {
      value: "MQ",
      flag: "https://flagcdn.com/w40/mq.png",
      country: { en: "Martinique", ar: "مارتينيك" },
      phone_code: "596",
      phoneLength: 9,
    },
    {
      value: "MR",
      flag: "https://flagcdn.com/w40/mr.png",
      country: { en: "Mauritania", ar: "موريتانيا" },
      phone_code: "222",
      phoneLength: 8,
    },
    {
      value: "MS",
      flag: "https://flagcdn.com/w40/ms.png",
      country: { en: "Montserrat", ar: "مونتسرات" },
      phone_code: "1-664",
      phoneLength: 10,
    },
    {
      value: "MT",
      flag: "https://flagcdn.com/w40/mt.png",
      country: { en: "Malta", ar: "مالطا" },
      phone_code: "356",
      phoneLength: 8,
    },
    {
      value: "MU",
      flag: "https://flagcdn.com/w40/mu.png",
      country: { en: "Mauritius", ar: "موريشيوس" },
      phone_code: "230",
      phoneLength: 8,
    },
    {
      value: "MV",
      flag: "https://flagcdn.com/w40/mv.png",
      country: { en: "Maldives", ar: "جزر المالديف" },
      phone_code: "960",
      phoneLength: 7,
    },
    {
      value: "MW",
      flag: "https://flagcdn.com/w40/mw.png",
      country: { en: "Malawi", ar: "ملاوي" },
      phone_code: "265",
      phoneLength: [7, 8, 9],
    },
    {
      value: "MX",
      flag: "https://flagcdn.com/w40/mx.png",
      country: { en: "Mexico", ar: "المكسيك" },
      phone_code: "52",
      phoneLength: 10,
    },
    {
      value: "MY",
      flag: "https://flagcdn.com/w40/my.png",
      country: { en: "Malaysia", ar: "ماليزيا" },
      phone_code: "60",
      phoneLength: 7,
    },
    {
      value: "MZ",
      flag: "https://flagcdn.com/w40/mz.png",
      country: { en: "Mozambique", ar: "موزمبيق" },
      phone_code: "258",
      phoneLength: 12,
    },
    {
      value: "NA",
      flag: "https://flagcdn.com/w40/na.png",
      country: { en: "Namibia", ar: "ناميبيا" },
      phone_code: "264",
      phoneLength: 7,
    },
    {
      value: "NC",
      flag: "https://flagcdn.com/w40/nc.png",
      country: { en: "New Caledonia", ar: "كاليدونيا الجديدة" },
      phone_code: "687",
      phoneLength: 6,
    },
    {
      value: "NE",
      flag: "https://flagcdn.com/w40/ne.png",
      country: { en: "Niger", ar: "النيجر" },
      phone_code: "227",
      phoneLength: 8,
    },
    {
      value: "NF",
      flag: "https://flagcdn.com/w40/nf.png",
      country: { en: "Norfolk Island", ar: "جزيرة نورفولك" },
      phone_code: "672",
      phoneLength: 6,
    },
    {
      value: "NG",
      flag: "https://flagcdn.com/w40/ng.png",
      country: { en: "Nigeria", ar: "نيجيريا" },
      phone_code: "234",
      phoneLength: 8,
    },
    {
      value: "NI",
      flag: "https://flagcdn.com/w40/ni.png",
      country: { en: "Nicaragua", ar: "نيكاراغوا" },
      phone_code: "505",
      phoneLength: 8,
    },
    {
      value: "NL",
      flag: "https://flagcdn.com/w40/nl.png",
      country: { en: "Netherlands", ar: "هولندا" },
      phone_code: "31",
      phoneLength: 9,
    },
    {
      value: "NO",
      flag: "https://flagcdn.com/w40/no.png",
      country: { en: "Norway", ar: "النرويج" },
      phone_code: "47",
      phoneLength: 8,
    },
    {
      value: "NP",
      flag: "https://flagcdn.com/w40/np.png",
      country: { en: "Nepal", ar: "نيبال" },
      phone_code: "977",
      phoneLength: 10,
    },
    {
      value: "NR",
      flag: "https://flagcdn.com/w40/nr.png",
      country: { en: "Nauru", ar: "ناورو" },
      phone_code: "674",
      phoneLength: 7,
    },
    {
      value: "NU",
      flag: "https://flagcdn.com/w40/nu.png",
      country: { en: "Niue", ar: "نيوي" },
      phone_code: "683",
      phoneLength: 4,
    },
    {
      value: "NZ",
      flag: "https://flagcdn.com/w40/nz.png",
      country: { en: "New Zealand", ar: "نيوزيلندا" },
      phone_code: "64",
      phoneLength: [8, 9],
    },
    {
      value: "OM",
      flag: "https://flagcdn.com/w40/om.png",
      country: { en: "Oman", ar: "عمان" },
      phone_code: "968",
      phoneLength: 8,
    },
    {
      value: "PA",
      flag: "https://flagcdn.com/w40/pa.png",
      country: { en: "Panama", ar: "بنما" },
      phone_code: "507",
      phoneLength: 8,
    },
    {
      value: "PE",
      flag: "https://flagcdn.com/w40/pe.png",
      country: { en: "Peru", ar: "بيرو" },
      phone_code: "51",
      phoneLength: 9,
    },
    {
      value: "PF",
      flag: "https://flagcdn.com/w40/pf.png",
      country: { en: "French Polynesia", ar: "بولينيزيا الفرنسية" },
      phone_code: "689",
      phoneLength: 8,
    },
    {
      value: "PG",
      flag: "https://flagcdn.com/w40/pg.png",
      country: { en: "Papua New Guinea", ar: "بابوا غينيا الجديدة" },
      phone_code: "675",
      phoneLength: 8,
    },
    {
      value: "PH",
      flag: "https://flagcdn.com/w40/ph.png",
      country: { en: "Philippines", ar: "الفلبين" },
      phone_code: "63",
      phoneLength: 10,
    },
    {
      value: "PK",
      flag: "https://flagcdn.com/w40/pk.png",
      country: { en: "Pakistan", ar: "باكستان" },
      phone_code: "92",
      phoneLength: 10,
    },
    {
      value: "PL",
      flag: "https://flagcdn.com/w40/pl.png",
      country: { en: "Poland", ar: "بولندا" },
      phone_code: "48",
      phoneLength: 9,
    },
    {
      value: "PM",
      flag: "https://flagcdn.com/w40/pm.png",
      country: { en: "Saint Pierre and Miquelon", ar: "سان بيير وميكلون" },
      phone_code: "508",
      phoneLength: 6,
    },
    {
      value: "PN",
      flag: "https://flagcdn.com/w40/pn.png",
      country: { en: "Pitcairn", ar: "جزر بيتكيرن" },
      phone_code: "870",
      phoneLength: 9,
    },
    {
      value: "PR",
      flag: "https://flagcdn.com/w40/pr.png",
      country: { en: "Puerto Rico", ar: "بورتوريكو" },
      phone_code: "1",
      phoneLength: 10,
    },
    {
      value: "PS",
      flag: "https://flagcdn.com/w40/ps.png",
      country: { en: "Palestine, State of", ar: "فلسطين" },
      phone_code: "970",
      phoneLength: 9,
    },
    {
      value: "PT",
      flag: "https://flagcdn.com/w40/pt.png",
      country: { en: "Portugal", ar: "البرتغال" },
      phone_code: "351",
      phoneLength: 9,
    },
    {
      value: "PW",
      flag: "https://flagcdn.com/w40/pw.png",
      country: { en: "Palau", ar: "بالاو" },
      phone_code: "680",
      phoneLength: 7,
    },
    {
      value: "PY",
      flag: "https://flagcdn.com/w40/py.png",
      country: { en: "Paraguay", ar: "باراغواي" },
      phone_code: "595",
      phoneLength: 9,
    },
    {
      value: "QA",
      flag: "https://flagcdn.com/w40/qa.png",
      country: { en: "Qatar", ar: "قطر" },
      phone_code: "974",
      phoneLength: 8,
    },
    {
      value: "RE",
      flag: "https://flagcdn.com/w40/re.png",
      country: { en: "Reunion", ar: "لا ريونيون" },
      phone_code: "262",
      phoneLength: 10,
    },
    {
      value: "RO",
      flag: "https://flagcdn.com/w40/ro.png",
      country: { en: "Romania", ar: "رومانيا" },
      phone_code: "40",
      phoneLength: 10,
    },
    {
      value: "RU",
      flag: "https://flagcdn.com/w40/ru.png",
      country: { en: "Russia", ar: "روسيا" },
      phone_code: "7",
      phoneLength: 10,
    },
    {
      value: "RW",
      flag: "https://flagcdn.com/w40/rw.png",
      country: { en: "Rwanda", ar: "رواندا" },
      phone_code: "250",
      phoneLength: 9,
    },
    {
      value: "SA",
      flag: "https://flagcdn.com/w40/sa.png",
      country: { en: "Saudi Arabia", ar: "المملكة العربية السعودية" },
      phone_code: "966",
      phoneLength: 9,
    },
    {
      value: "SB",
      flag: "https://flagcdn.com/w40/sb.png",
      country: { en: "Solomon Islands", ar: "جزر سليمان" },
      phone_code: "677",
      phoneLength: 7,
    },
    {
      value: "SC",
      flag: "https://flagcdn.com/w40/sc.png",
      country: { en: "Seychelles", ar: "سيشيل" },
      phone_code: "248",
      phoneLength: 7,
    },
    {
      value: "SD",
      flag: "https://flagcdn.com/w40/sd.png",
      country: { en: "Sudan", ar: "السودان" },
      phone_code: "249",
      phoneLength: 9,
    },
    {
      value: "SE",
      flag: "https://flagcdn.com/w40/se.png",
      country: { en: "Sweden", ar: "السويد" },
      phone_code: "46",
      phoneLength: 9,
    },
    {
      value: "SG",
      flag: "https://flagcdn.com/w40/sg.png",
      country: { en: "Singapore", ar: "سنغافورة" },
      phone_code: "65",
      phoneLength: 8,
    },
    {
      value: "SH",
      flag: "https://flagcdn.com/w40/sh.png",
      country: { en: "Saint Helena", ar: "سانت هيلينا" },
      phone_code: "290",
      phoneLength: 4,
    },
    {
      value: "SI",
      flag: "https://flagcdn.com/w40/si.png",
      country: { en: "Slovenia", ar: "سلوفينيا" },
      phone_code: "386",
      phoneLength: 8,
    },
    {
      value: "SJ",
      flag: "https://flagcdn.com/w40/sj.png",
      country: { en: "Svalbard and Jan Mayen", ar: "سفالبارد ويان ماين" },
      phone_code: "47",
      phoneLength: 8,
    },
    {
      value: "SK",
      flag: "https://flagcdn.com/w40/sk.png",
      country: { en: "Slovakia", ar: "سلوفاكيا" },
      phone_code: "421",
      phoneLength: 9,
    },
    {
      value: "SL",
      flag: "https://flagcdn.com/w40/sl.png",
      country: { en: "Sierra Leone", ar: "سيراليون" },
      phone_code: "232",
      phoneLength: 8,
    },
    {
      value: "SM",
      flag: "https://flagcdn.com/w40/sm.png",
      country: { en: "San Marino", ar: "سان مارينو" },
      phone_code: "378",
      phoneLength: 10,
    },
    {
      value: "SN",
      flag: "https://flagcdn.com/w40/sn.png",
      country: { en: "Senegal", ar: "السنغال" },
      phone_code: "221",
      phoneLength: 9,
    },
    {
      value: "SO",
      flag: "https://flagcdn.com/w40/so.png",
      country: { en: "Somalia", ar: "الصومال" },
      phone_code: "252",
      phoneLength: 8,
    },
    {
      value: "SR",
      flag: "https://flagcdn.com/w40/sr.png",
      country: { en: "Suriname", ar: "سورينام" },
      phone_code: "597",
      phoneLength: 7,
    },
    {
      value: "SS",
      flag: "https://flagcdn.com/w40/ss.png",
      country: { en: "South Sudan", ar: "جنوب السودان" },
      phone_code: "211",
      phoneLength: 9,
    },
    {
      value: "ST",
      flag: "https://flagcdn.com/w40/st.png",
      country: { en: "Sao Tome and Principe", ar: "ساو تومي وبرينسيبي" },
      phone_code: "239",
      phoneLength: 7,
    },
    {
      value: "SV",
      flag: "https://flagcdn.com/w40/sv.png",
      country: { en: "El Salvador", ar: "السلفادور" },
      phone_code: "503",
      phoneLength: 8,
    },
    {
      value: "SX",
      flag: "https://flagcdn.com/w40/sx.png",
      country: { en: "Sint Maarten", ar: "سينت مارتن" },
      phone_code: "1-721",
      phoneLength: 10,
    },
    {
      value: "SY",
      flag: "https://flagcdn.com/w40/sy.png",
      country: { en: "Syrian Arab Republic", ar: "سوريا" },
      phone_code: "963",
      phoneLength: 9,
    },
    {
      value: "SZ",
      flag: "https://flagcdn.com/w40/sz.png",
      country: { en: "Swaziland", ar: "سوازيلاند" },
      phone_code: "268",
      phoneLength: 8,
    },
    {
      value: "TC",
      flag: "https://flagcdn.com/w40/tc.png",
      country: { en: "Turks and Caicos Islands", ar: "جزر توركس وكايكوس" },
      phone_code: "1-649",
      phoneLength: 10,
    },
    {
      value: "TD",
      flag: "https://flagcdn.com/w40/td.png",
      country: { en: "Chad", ar: "تشاد" },
      phone_code: "235",
      phoneLength: 8,
    },
    {
      value: "TF",
      flag: "https://flagcdn.com/w40/tf.png",
      country: {
        en: "French Southern Territories",
        ar: "المقاطعات الجنوبية الفرنسية",
      },
      phone_code: "262",
      phoneLength: 9,
    },
    {
      value: "TG",
      flag: "https://flagcdn.com/w40/tg.png",
      country: { en: "Togo", ar: "توغو" },
      phone_code: "228",
      phoneLength: 8,
    },
    {
      value: "TH",
      flag: "https://flagcdn.com/w40/th.png",
      country: { en: "Thailand", ar: "تايلاند" },
      phone_code: "66",
      phoneLength: 9,
    },
    {
      value: "TJ",
      flag: "https://flagcdn.com/w40/tj.png",
      country: { en: "Tajikistan", ar: "طاجيكستان" },
      phone_code: "992",
      phoneLength: 9,
    },
    {
      value: "TK",
      flag: "https://flagcdn.com/w40/tk.png",
      country: { en: "Tokelau", ar: "توكيلاو" },
      phone_code: "690",
      phoneLength: 4,
    },
    {
      value: "TL",
      flag: "https://flagcdn.com/w40/tl.png",
      country: { en: "Timor-Leste", ar: "تيمور الشرقية" },
      phone_code: "670",
      phoneLength: 8,
    },
    {
      value: "TM",
      flag: "https://flagcdn.com/w40/tm.png",
      country: { en: "Turkmenistan", ar: "تركمانستان" },
      phone_code: "993",
      phoneLength: 8,
    },
    {
      value: "TN",
      flag: "https://flagcdn.com/w40/tn.png",
      country: { en: "Tunisia", ar: "تونس" },
      phone_code: "216",
      phoneLength: 8,
    },
    {
      value: "TO",
      flag: "https://flagcdn.com/w40/to.png",
      country: { en: "Tonga", ar: "تونغا" },
      phone_code: "676",
      phoneLength: 7,
    },
    {
      value: "TR",
      flag: "https://flagcdn.com/w40/tr.png",
      country: { en: "Turkey", ar: "تركيا" },
      phone_code: "90",
      phoneLength: 10,
    },
    {
      value: "TT",
      flag: "https://flagcdn.com/w40/tt.png",
      country: { en: "Trinidad and Tobago", ar: "ترينيداد وتوباغو" },
      phone_code: "1-868",
      phoneLength: 10,
    },
    {
      value: "TV",
      flag: "https://flagcdn.com/w40/tv.png",
      country: { en: "Tuvalu", ar: "توفالو" },
      phone_code: "688",
      phoneLength: 5,
    },
    {
      value: "TW",
      flag: "https://flagcdn.com/w40/tw.png",
      country: { en: "Taiwan", ar: "تايوان" },
      phone_code: "886",
      phoneLength: 9,
    },
    {
      value: "TZ",
      flag: "https://flagcdn.com/w40/tz.png",
      country: { en: "Tanzania", ar: "تنزانيا" },
      phone_code: "255",
      phoneLength: 9,
    },
    {
      value: "UA",
      flag: "https://flagcdn.com/w40/ua.png",
      country: { en: "Ukraine", ar: "أوكرانيا" },
      phone_code: "380",
      phoneLength: 9,
    },
    {
      value: "UG",
      flag: "https://flagcdn.com/w40/ug.png",
      country: { en: "Uganda", ar: "أوغندا" },
      phone_code: "256",
      phoneLength: 9,
    },
    {
      value: "UM",
      flag: "https://flagcdn.com/w40/um.png",
      country: {
        en: "United States Minor Outlying Islands",
        ar: "جزر الولايات المتحدة الصغيرة النائية",
      },
      phone_code: "1",
      phoneLength: 10,
    },
    {
      value: "US",
      flag: "https://flagcdn.com/w40/us.png",
      country: { en: "United States", ar: "الولايات المتحدة الأمريكية" },
      phone_code: "1",
      suggested: true,
      phoneLength: 10,
    },
    {
      value: "UY",
      flag: "https://flagcdn.com/w40/uy.png",
      country: { en: "Uruguay", ar: "أوروغواي" },
      phone_code: "598",
      phoneLength: 8,
    },
    {
      value: "UZ",
      flag: "https://flagcdn.com/w40/uz.png",
      country: { en: "Uzbekistan", ar: "أوزبكستان" },
      phone_code: "998",
      phoneLength: 9,
    },
    {
      value: "VA",
      flag: "https://flagcdn.com/w40/va.png",
      country: { en: "Holy See (Vatican City State)", ar: "الفاتيكان" },
      phone_code: "379",
      phoneLength: 10,
    },
    {
      value: "VC",
      flag: "https://flagcdn.com/w40/vc.png",
      country: {
        en: "Saint Vincent and the Grenadines",
        ar: "سانت فنسنت والغرينادين",
      },
      phone_code: "1-784",
      phoneLength: 10,
    },
    {
      value: "VE",
      flag: "https://flagcdn.com/w40/ve.png",
      country: { en: "Venezuela", ar: "فنزويلا" },
      phone_code: "58",
      phoneLength: 10,
    },
    {
      value: "VG",
      flag: "https://flagcdn.com/w40/vg.png",
      country: { en: "Virgin Islands, British", ar: "جزر العذراء البريطانية" },
      phone_code: "1-284",
      phoneLength: 10,
    },
    {
      value: "VI",
      flag: "https://flagcdn.com/w40/vi.png",
      country: { en: "Virgin Islands, U.S.", ar: "جزر العذراء الأمريكية" },
      phone_code: "1-340",
      phoneLength: 10,
    },
    {
      value: "VN",
      flag: "https://flagcdn.com/w40/vn.png",
      country: { en: "Vietnam", ar: "فيتنام" },
      phone_code: "84",
      phoneLength: 9,
    },
    {
      value: "VU",
      flag: "https://flagcdn.com/w40/vu.png",
      country: { en: "Vanuatu", ar: "فانواتو" },
      phone_code: "678",
      phoneLength: 7,
    },
    {
      value: "WF",
      flag: "https://flagcdn.com/w40/wf.png",
      country: { en: "Wallis and Futuna", ar: "واليس وفوتونا" },
      phone_code: "681",
      phoneLength: 6,
    },
    {
      value: "WS",
      flag: "https://flagcdn.com/w40/ws.png",
      country: { en: "Samoa", ar: "ساموا" },
      phone_code: "685",
      phoneLength: 7,
    },
    {
      value: "YE",
      flag: "https://flagcdn.com/w40/ye.png",
      country: { en: "Yemen", ar: "اليمن" },
      phone_code: "967",
      phoneLength: 9,
    },
    {
      value: "YT",
      flag: "https://flagcdn.com/w40/yt.png",
      country: { en: "Mayotte", ar: "مايوت" },
      phone_code: "262",
      phoneLength: 9,
    },
    {
      value: "ZA",
      flag: "https://flagcdn.com/w40/za.png",
      country: { en: "South Africa", ar: "جنوب أفريقيا" },
      phone_code: "27",
      phoneLength: 9,
    },
    {
      value: "ZM",
      flag: "https://flagcdn.com/w40/zm.png",
      country: { en: "Zambia", ar: "زامبيا" },
      phone_code: "260",
      phoneLength: 9,
    },
    {
      value: "ZW",
      flag: "https://flagcdn.com/w40/zw.png",
      country: { en: "Zimbabwe", ar: "زيمبابوي" },
      phone_code: "263",
      phoneLength: 9,
    },
  ]